# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "lV5DBqgCTAthrOH7DO87TNNWqhVm4cWQLDyKq1jBfWbJza4ITinX2Mzx28jeB4IziNfW7lMUs+WXM3Dobwbwaosz5q8U6JfJzQAwrV/rxvZRilfDMnF/8C/dpEa0Ie5ct0d5XeSJ9RnOCcWgP9UQ8D9gE1lA1pJD1AC057g3HJIor8C27D7NWPI7E4DyE69sad4RU+PKi6OXE9k1l+Mc2FxWQPdwikNvq2oNncsIjfg8Lblzi+aFRqYLmdM/ZAq+N+znZrhk9eQ0QRrGbPno0JLG2U+ae+X+UF5GMprqOrN+9sLfth4T+jy2Muv21rSrhiOdsga9Avurj/uh5vd50iN0WXiK14yp4ls7yPJvn0mSHozQkQ/tSwvhtEJe6QhGBSOAbu7YgRWvc8CnR29S0Pu5t5lz8X1+792AL11/FB5DUkHZOKXnsdIJf9D6t1WueJzARVzhcCoRyzO8E5ZdwFtbChfIRUg8CbU4r/69hHemnCYCRRZc1kb8jXnsFxHz9x4Wqf8x8glIaB+0VKsm6Co77gX5LiEaBSatA5ZfHHYE20MM3S7J/YBXVbAbDg9/eE3X+hH5utcRcXMTUKQzuY2gpvQWldnsJkuk2SyE3Ym6nZXYnzqRWZoMoLJiA0SHF584tUrfRKYwNW4QDKHYk3kxoLRStqXMJYEYDe8MNvY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
