travis:
  secure:
    BINSTAR_TOKEN: lV5DBqgCTAthrOH7DO87TNNWqhVm4cWQLDyKq1jBfWbJza4ITinX2Mzx28jeB4IziNfW7lMUs+WXM3Dobwbwaosz5q8U6JfJzQAwrV/rxvZRilfDMnF/8C/dpEa0Ie5ct0d5XeSJ9RnOCcWgP9UQ8D9gE1lA1pJD1AC057g3HJIor8C27D7NWPI7E4DyE69sad4RU+PKi6OXE9k1l+Mc2FxWQPdwikNvq2oNncsIjfg8Lblzi+aFRqYLmdM/ZAq+N+znZrhk9eQ0QRrGbPno0JLG2U+ae+X+UF5GMprqOrN+9sLfth4T+jy2Muv21rSrhiOdsga9Avurj/uh5vd50iN0WXiK14yp4ls7yPJvn0mSHozQkQ/tSwvhtEJe6QhGBSOAbu7YgRWvc8CnR29S0Pu5t5lz8X1+792AL11/FB5DUkHZOKXnsdIJf9D6t1WueJzARVzhcCoRyzO8E5ZdwFtbChfIRUg8CbU4r/69hHemnCYCRRZc1kb8jXnsFxHz9x4Wqf8x8glIaB+0VKsm6Co77gX5LiEaBSatA5ZfHHYE20MM3S7J/YBXVbAbDg9/eE3X+hH5utcRcXMTUKQzuY2gpvQWldnsJkuk2SyE3Ym6nZXYnzqRWZoMoLJiA0SHF584tUrfRKYwNW4QDKHYk3kxoLRStqXMJYEYDe8MNvY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
